### ISSUE TITLE
root required, then exit.

### ISSUE THREAD

**Issue by gousern** [MatteCarra/AccA#149]
> Environment

Magisk :21.4
Magisk Manager: 8.0.7
MagiskHide：All my installed apps with MagiskHide enabled.
ACC：v2020.11.20
AccA：1.0.30
OS: Android 7.1.3
Phone Model: none-rooted xiaomi 4x

> Steps

1. From the magisk manager, AccA has granted root permission. 
2. AccA works a while at first installation.
3. Enable MagiskHide to AccA
4. Phone rebooted 
5. Open AccA, it shows root required then exit. 

> Solution

Disable the MagiskHide to AccA, then AccA works. 

> Question

Since AccA has granted root permission by Magisk Manager successfully, is there a fasle positive result exists in AccA?
(this ticket is similar to issue No.[ 87](https://github.com/MatteCarra/AccA/issues/87)

**Comment by squabbi** [comment]
Hi there! #87 seems to be referencing when Magisk Manager is hidden (i.e. repackaged). Which is something different than what you have.

You've chosen to hide Magisk from AccA which means it won't be able to access the su libraries/binaries in order to attain root access. The app requires root access to function, so hiding Magisk from it would result in it thinking you're not rooted, although previously granted.

Same happens if I do the same steps with Termux, once hidden I can't elevate the shell. After removing Termux from Magisk Hide and rebooting, it can access su again.

I believe this is the intended behaviour, if you have an example that shows otherwise, feel free to re-open this issue.
