### ISSUE TITLE
acca kinda bugged on latest update

### ISSUE THREAD

**Issue by kevin01523** [MatteCarra/AccA#189]
![Screenshot_20210831-200949](https://user-images.githubusercontent.com/8380242/131500260-1342226d-a30d-48b9-a1be-997ee4861552.jpg)
![Screenshot_20210831-200958](https://user-images.githubusercontent.com/8380242/131500275-cc7660fc-3c12-41b6-94a9-189b03029124.jpg)
![Screenshot_20210831-201013](https://user-images.githubusercontent.com/8380242/131500283-bcafe14b-a0e2-4e1b-a3da-9ef34450b22a.jpg)

i think this related to the latest update of acc which kinda broke both acca and acc

**Comment by ghost** [comment]
I can confirm this issue occurs on my S10e with LineageOS 18.1 only with the latest release.

**Comment by VR-25** [comment]
https://github.com/VR-25/acc/issues/113

**Comment by VR-25** [comment]
@MatteCarra, @nialone, this seems to have been introduced by a pull request.
Someone just confirmed that the previous AccA version does not have this issue when paired with the latest acc.

**Comment by MatteCarra** [comment]
Can you please confirm me that the only problematic screen is the acc settings screen?

**Comment by nialone** [comment]
It is difficult for me to disassemble all the problems because of the language barrier. I realized that there are 2 problems, it is a current and configuration editor. In my last personal assembly all the work!

I can confirm that the editor has already been corrected.
He expects to branch on a confirmation. [Fix AccEditor](https://github.com/nialone/AccA/commit/82ac445ac4187b0c6071e4d91866784bab3fae41)

The problem with the current was not affected, except for the discordation of the sign. It is easy to check on the device. Connect charging, execute the command: "ACC -i", see what value in the CURRENT_NOW parameter.

**Comment by kevin01523** [comment]
yes the only issue is config editor  on the dashboard and on the profiles tab

**Comment by VR-25** [comment]
I fixed the 0 mA current issue.
A new acc version will be pushed once you guys show me a green light.
[acc_v2021.8.31_(202108310).zip](https://github.com/MatteCarra/AccA/files/7084557/acc_v2021.8.31_.202108310.zip) @kevin01523, this should work with the previous AccA.
[acc_v2021.8.31_(202108310).tar.gz](https://github.com/MatteCarra/AccA/files/7084556/acc_v2021.8.31_.202108310.tar.gz)

**Comment by MatteCarra** [comment]
https://github.com/MatteCarra/AccA/releases/tag/v1.0.35

**Comment by kevin01523** [comment]
thanks it works now just needs to test if there's more bugs
