### ISSUE TITLE
Pixel 6 / Pixel 6 pro Support?

### ISSUE THREAD

**Issue by filo4u** [MatteCarra/AccA#200]
Is the Pixel 6 & Pixel 6 pro supported yet? ACC Daemon keeps crashing and not sure if this is only happening on my phone. Thank you in advance!
![Screenshot_20211209-120331](https://user-images.githubusercontent.com/20917155/145467842-f591ec2d-4450-440e-b4d5-2f54821ad262.png)

**Comment by VR-25** [comment]
The daemon is not crashing
It stops intentionally, since there's no supported charging switch.

[acc_v2021.12.5_202112050.zip](https://github.com/MatteCarra/AccA/files/7688145/acc_v2021.12.5_202112050.zip)
This pre-release supports the Pixel 6/Pro. Install from Magisk manager. No reboot/setup required.

**Comment by filo4u** [comment]
You're amazing! Thank you very much.
