### ISSUE TITLE
files under /sdcard/

### ISSUE THREAD

**Issue by 0xRR** [MatteCarra/AccA#50]
There are more and more files and folder under /sdcard/ .
It will be very thankful if you put them under /sdcard/Android/data/mattecarra.accapp .

**Comment by VR-25** [comment]
Which folders are you referring to, specifically?
The app doesn't store anything in user storage.
In fact, it doesn't even have user storage access permissions.

**Comment by 0xRR** [comment]
ACCA_v1.0.11(16) has only an folder names "/acc" .
ACCA_v1.0.12(17) has an folder names "/acc-data" and a file names “.acc-config-backup.txt” .

**Comment by VR-25** [comment]
These are created by the back-end (acc). You can safely delete `/sdcard/acc-data/`. It's an artifact.

Now we're left with `/sdcard/.acc-config-backup.txt`. This file is there to survive TWRP factory resets. The actual config is stored at `/data/adb/acc-data/config.txt`.

The backup file can't be stored at `/sdcard/Android/data/mattecarra.accapp/`, because ACC itself is independent. Besides, this would interfere with other front-ends.

**Comment by 0xRR** [comment]
> These are created by the back-end (acc). You can safely delete `/sdcard/acc-data/`. It's an artifact.
> 
> Now we're left with `/sdcard/.acc-config-backup.txt`. This file is there to survive TWRP factory resets. The actual config is stored at `/data/adb/acc-data/config.txt`.
> 
> The backup file can't be stored at `/sdcard/Android/data/mattecarra.accapp/`, because ACC itself is independent. Besides, this would interfere with other front-ends.

Thanks for the explanation ! 

I see , my fault , apologises !
