### ISSUE TITLE
[Feature Request] Reset battery stats when it reaches a target percentage

### ISSUE THREAD

**Issue by Mar2ck** [MatteCarra/AccA#80]
I have acc set to never go past 80% charge so the better stats don't get reset after a full charge like they normally would. Hopefully a feature like this wouldn't be too hard to implement

**Comment by VR-25** [comment]
`resetBsOnPause` has been around since the early days.
This feature lets acc reset battery status after max capacity is reached (i.e., 80%, in your case).
To enable it, run `su -c acc -s resetBsOnPause true`.

There's also `resetBsOnUnplug`.
The name is self-explanatory.
The enabling procedure is similar to the previous'.
Unlike the first, this can be toggled from the app.

**Comment by VR-25** [comment]
#81
